disable_grub: false

system_packages:
  - acl
  - mc
  - htop
  - atop
  - iotop
  - rsync
  - curl
  - wget
  - unzip

kafka_version: 3.3.1
zookeeper_version: 3.8.0

http_proxy: ""
https_proxy: ""

# Apache Kafka properties:
default_replication_factor: 2
num_partitions: 16
log_retention_hours: 48
log_dirs: "/var/lib/kafka"
